# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=10000)),
                ('question_marks', models.IntegerField()),
                ('input_format', models.CharField(max_length=1000)),
                ('output_format', models.CharField(max_length=1000)),
                ('sample_input', models.CharField(max_length=1000)),
                ('sample_output', models.CharField(max_length=1000)),
                ('constraints', models.CharField(max_length=1000)),
                ('explanation', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('team_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('member_1_name', models.CharField(max_length=30)),
                ('member_1_phone_no', models.IntegerField()),
                ('member_1_email', models.EmailField(max_length=30)),
                ('member_2_name', models.CharField(blank=True, max_length=30, null=True)),
                ('member_2_phone_no', models.IntegerField(blank=True, null=True)),
                ('member_2_email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('team_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(max_length=10000)),
                ('program_code', models.TextField()),
                ('time', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginTime',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('login_time', models.CharField(max_length=30)),
            ],
        ),
    ]
