# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeaton', '0002_auto_20170220_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='input_format',
            field=models.CharField(default='asdasdasdasfsdvad', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='output_format',
            field=models.CharField(default='adfhhsdffdghjkujytrefdasxzcvbnhjy', max_length=1000),
            preserve_default=False,
        ),
    ]
