# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeaton', '0003_auto_20170519_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
    ]
