# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeaton', '0005_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='member_1_phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='member_2_phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
